### ISSUE TITLE
CoffeeScript

### ISSUE THREAD

**Issue by Raynos** [tbergeron/ThinAir#2]
ಠ_ಠ

**Comment by tbergeron** [comment]
I laughed a lot when I woke up and saw this in my emails.

I knew that at the exact time I'd merge this coffeescript branch I'd get hate mails ;-)

I'm testing it out, heard a lot of good things, and bad things and so far I like the "cleaner, shorter code" and the functionality that it adds over JS, but I'm still unsure about how it'll turn out on the long run.

Any experiences or other comments to share?

**Comment by Raynos** [comment]
> Comments to share

I'm not going to list your app as an example because it uses CoffeeScript.

CoffeeScript is a very silly language, I refuse to read and write it merely because dealing with CoffeeScript is a waste of time. 

Your restricting yourself to the subset of JS developers who care / tolerate CoffeeScript. 

nodeup made a nice comment on coffeescript recently.

I highly recommend you to go back to sensible JS

**Comment by tbergeron** [comment]
> I'm not going to list your app as an example because it uses CoffeeScript.

:'-( My world is being torn apart between the Pure JS world and the CoffeeScript world. I was the first in my office to bash on CoffeeScript. People call me "vane" because I always change my opinions (which is a good thing IMO). But since I switched I received many comments about this and I'm starting to think the other way...

> Your restricting yourself to the subset of JS developers who care / tolerate CoffeeScript.

This is a very good and convincing reason, I wanted to try it out, I honestly think there's good concepts in there, but there's still the "why add another layer of abstraction over javascript?" question I can't get over...

> nodeup made a nice comment on coffeescript recently.

Could you refer me to the page / episode? I looked on Google but found nothing really pertinent.

> I highly recommend you to go back to sensible JS

Don't worry, I'll deeply think about the pros and cons and I'll make a choice by the end of the day.

Edit: I'd just like to add that I'm a sucker for good/short syntax/code and that's what I really liked about it (Ruby-ish syntax)...

**Comment by Raynos** [comment]
Also do note that code like

`module.exports = start: start = (server) ->`

Is readable but retarded. It's like Why the hell is the `=` there, why doesn't that break

It turns into

```
var start
module.exports = { start: start = function (server) { ... } }
```

Which works but is redundant. (I didn't actually know assignment expressions are valid in object literals, this is very silly)

It's hard to tell whether your an idiot or coffeescript is doing something retarded.

As for nodeup in the last 10 minutes or so of (http://nodeup.com/) episode 17

**Comment by nickjj** [comment]
If it helps any, Raynos is telling me about ncore too and told me to look at your project. I noticed your project is in CS and stopped looking at it shortly after. I think your ideas and methods of using ncore/setting up a minimal skeleton app are interesting but there's a 0% chance I'd ever use it since I don't write CS.

It's painful enough just to read / context switch to JS on the fly when trying to port over certain ideas to JS.

I have nothing against the CS camp but keep in mind that most non-CS users will just find alternative libs to use that don't use CS -- especially if it's something they might end up forking/maintaining themselves.

**Comment by tbergeron** [comment]
@Raynos and @nickjj 

I wrote on a sheet of paper the pros and cons of JS vs CoffeeScript for my kind of project and I finally made the move back to JavaScript.

You both have very good points and thank you for debating them with me, I love to learn and to receive criticism.

> I have nothing against the CS camp but keep in mind that most non-CS users will just find alternative libs to use that don't use CS -- especially if it's something they might end up forking/maintaining themselves.

The lesson I learned today is that JavaScript is standard, and libraries/frameworks should more-than-everything follow those standards.

Thanks to both of you, you can read my code now ;-)

**Comment by nickjj** [comment]
Welcome back to JS land. I'll continue to keep an eye out on your project.

**Comment by tbergeron** [comment]
@nickjj Thanks =)

@Raynos NodeUp guys have really good points about it, I've just finished listening to the end of the podcast and the "less people will be willing to work on your project" is a very strong argument. Thanks for sharing!
